### ISSUE TITLE
Interface "Rammassable"

### ISSUE THREAD

**Issue by skeggib** [skeggib/ehptmmmorpgsvr#10]
Faire une interface "Rammassable" que Coffre et Objet implémenteront, elle contiendra la méthode "ListeUnique getListObjets()" (le Coffre renverra la liste de ses objets et Objet renverra une liste avec un seul objet).
De cette manière EntiteVivante pourra avoir une seule méthode "rammasser(Rammassable r)" qui ajoutera les objets de la liste à son inventaire.

@armiakrajowa : Ne la fait pas encore, il faut qu'on en parle pour voir si ça ne posera pas d'autres problèmes.

(Polyyyymoooorphiiiiiiisme !)

**Comment by armiakrajowa** [comment]
Ça ressemble un peu a du bricolage..
Le 2 juin 2015 9:14 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Pourquoi ? Pour moi ce serai globaliser un peu tout ce qu'on peu ramasser, en plus on pourra éventuellement créer d'autres classes Rammassables qui pourront être ramassées sans rien changer.

PS: On s'est foiré, on a écrit partout "rammasser" alors que ça s'écrit "ramasser"

**Comment by armiakrajowa** [comment]
Ouai j'avais un doute x) je corrigerais avec eclipse
 Le 2 juin 2015 9:18 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Du coup bonne idée ou pas ?

**Comment by armiakrajowa** [comment]
Ouai mais bon.. Qu'un objet retourne une liste contenant lui même.. C'est
un peu une blague quoi..
Le 2 juin 2015 9:20 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Bah si ça se voit pas de l'extérieur c'est bon

**Comment by armiakrajowa** [comment]
Mais le prof va lire le code
Le 2 juin 2015 10:12 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Perso je trouve ça correcte, ça permet de globaliser les choses
