### ISSUE TITLE
Noms des potions de dégâts

### ISSUE THREAD

**Issue by skeggib** [skeggib/ehptmmmorpgsvr#11]
Les potions de dégâts ont des noms d'armes.

**Comment by armiakrajowa** [comment]
Tu as pull...?
Le 2 juin 2015 9:40 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Nope, je vais le faire

**Comment by skeggib** [comment]
Bah maintenant elles ont des noms de potions de soin

**Comment by armiakrajowa** [comment]
Reglé.
