### ISSUE TITLE
Methode charger de Carte

### ISSUE THREAD

**Issue by armiakrajowa** [skeggib/ehptmmmorpgsvr#12]
Je lisais ton code et je suis tombé sur un truc un peu.. aberrant..
Dans `chargerFichier(chemin)` : 
```java
	public boolean chargerFichier(String chemin) { //TODO skeggib : Revoir cette methode
		
		// Lire le fichier
		String lines[] = LectureFichier.lireT(chemin);
		String str = new String();
		
		// Reconstituer les lines en une seule chaine
		for (int i = 0; i < lines.length; i++)
			str += lines[i] + "\n";
		
		this.chargerString(str);
		
		return true;
	}
```

A partir du tableau que renvoie `LectureFichier.lireT(chemin)` tu t'amuse a le remettre dans une seul chaîne de caractère alors que la méthode `LectureFichier.lireS(chemin)` fait la même chose.

Soit, tu choisis de reconstituer la chaîne a partir du tableau. Mais, dans `chargerString(str)` tu fais ceci des le début : 
```java 
String[] lignes = str.split("\n");
```

Donc je resume :
 - Tu utilises `LectureFichier.lireT()` pour ensuite en fait un simple `String` alors que `LectureFichier.lireS()` le fait.
 - Le String ainsi reconstitué est envoyé a `chargerString(str)` qui en refait un tableau A LA PREMIÈRE LIGNE!!

Solution : Passer le tableaux de String de `LectureFichier.lireT()` directement a `chargerString(str)` sans un refaire un String simple et qui n'aura plus besoin d'en refaire un tableau, puisque ça en est déjà un

**Comment by skeggib** [comment]
J'ai fais cette méthode avant que tu fasse lireS, du coup j'avais pas le chois, mais maintenant qu'il y a LectureRessource.lire, qui renvoi un String, j'envoi directement ce String là.

**Comment by armiakrajowa** [comment]
Non mais tu as tout lu? Parce que tu fais Tableau -> String -> Tableau.
Toi tu m'as dit que tu allais faire String -> Tableau alors que tu pourrais
faire Tableau tout court
Le 4 juin 2015 10:48 AM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Oui, maintenant je fais :

- LectureRessource.lire qui me retourne un string
- Je passe ce string a chargerString
- chargerString le transforme en tableau pour le lire

**Comment by armiakrajowa** [comment]
Alors que tu pourrais récupérer un tableau directement.. C'est un peu bidon
quoi..
Le 4 juin 2015 11:16 AM, "Sebastien Klasa" <notifications@github.com> a
écrit :
