### ISSUE TITLE
Retour de la méthode EntiteVivante.attaquer()

### ISSUE THREAD

**Issue by skeggib** [skeggib/ehptmmmorpgsvr#2]
J'aurai besoin que la méthode EntiteVivante.attaquer() retourne le nombre de dégâts qu'a subit la cible pour pouvoir l'afficher dans les logs, c'est possible ou ça va gêner si elle ne retourne plus un boolean ?

**Comment by armiakrajowa** [comment]
Non c'est bon je le ferais demain
Le 21 mai 2015 11:52 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :
