### ISSUE TITLE
Recherche d'Objets avec contains

### ISSUE THREAD

**Issue by skeggib** [skeggib/ehptmmmorpgsvr#3]
Vérifie que tu n'utilise pas la méthode contains lorsque tu fais des recherches dans les ArrayList : cette méthode ne recherche pas un objet qui a la même référence mais qui est "equals".

Dans le cas des Objets tu ne pourra par exemple pas ajouter deux objets distincts qui ont les mêmes caractéristiques.

La solution serait de faire un boucle qui parcours l'ArrayList et de tester :
`list.get(i) == obj`

A moins qu'il existe déjà une méthode d'ArrayList qui le fait.

PS: Vu que tu n'as pas redéfini `Objet.equals(Object o)` je ne pense pas que ça pose de problèmes actuellement, mais il vaut mieux faire un test d'égalité (==) au cas où un jour tu redéfini equals.

**Comment by armiakrajowa** [comment]
Je redefinirai pas equal
Le 22 mai 2015 11:17 AM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Ce serait quand même plus propre de mettre des == je pense.

**Comment by armiakrajowa** [comment]
Ben y a une méthode faite pour autant l'utiliser
Le 22 mai 2015 12:02 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Non parce qu'elle ne fait pas ce que tu veux

**Comment by armiakrajowa** [comment]
Ben si puisque ça marche. Je testerais et au pire je redefinierais la
méthode.
Le 22 mai 2015 12:40 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :

> Non parce qu'elle ne fait pas ce que tu veux

**Comment by skeggib** [comment]
C'est pas parce que ça marche que c'est correcte.

Dans inventaire tu ne peut pas ajoute deux fois le même objet (la même
référence), tu doit donc utiliser ==
Mais si tu redéfinie equals et que tu garde contains tu ne pourra pas
ajouter deux objets qui ont les même caracteristiques

**Comment by armiakrajowa** [comment]
Je vais redéfinir CONTAINS j'ai dis ^^
Le 22 mai 2015 12:52 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :

> C'est pas parce que ça marche que c'est correcte.
>
> Dans inventaire tu ne peut pas ajoute deux fois le même objet (la même
> référence), tu doit donc utiliser ==
> Mais si tu redéfinie equals et que tu garde contains tu ne pourra pas
> ajouter deux objets qui ont les même caracteristiques

**Comment by skeggib** [comment]
Ah ok, de la classe ListeUnique ?

**Comment by armiakrajowa** [comment]
C'est ça ! Donc je ferais des test et je verrais bien
Le 22 mai 2015 3:08 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :
