### ISSUE TITLE
Bug équipement d'arme

### ISSUE THREAD

**Issue by skeggib** [skeggib/ehptmmmorpgsvr#6]
Il arrive que l'équipement d'arme ne marche pas.
Ce serait bien de mettre des throw dans les méthodes qui gèrent ça pour pouvoir récupérer l'erreur.
Je t'expliquerai comment j'organise les exceptions.

/cc @armiakrajowa

**Comment by armiakrajowa** [comment]
Bug non reproductible.. Si tu peux faire une screen ou autre j'arriverais peut etre a corriger

**Comment by armiakrajowa** [comment]
J'ai fait une boucle qui cree une arme a chaque tour, la rammasse, l'equipe si possible, puis desequipe une arme, en reequipe une autre, tout ca bien pratiquement, je l'ai fait plusieurs fois sur une boucle de 100000... Jamais eu d'erreur.
```java
		Joueur j = new Joueur("Armya");
		
		for(int i = 0; i < 100000; i++){
			Arme a = new Arme();
			j.rammasserObjet(a);
			j.equiperObjet(a);
			if((i%2) == 0){
				j.desequiperObjet(j.getEquipement().getObjet(1));
			}
			if((i%4) == 0){
				j.desequiperObjet(j.getEquipement().getObjet(0));
			}
			System.out.println("L'EQUIPEMENT CONTIENT " + j.getEquipement().getTaille() + " OBJETS");
			System.out.println("L'INVENTAIREd CONTIENT " + j.getInventaire().getTaille() + " OBJETS");
		}
```

**Comment by skeggib** [comment]
Bon, je ferme l'issue et je te dirai si ça se reproduit
