### ISSUE TITLE
Fin de tour

### ISSUE THREAD

**Issue by armiakrajowa** [skeggib/ehptmmmorpgsvr#7]
Quand le joueur n'a plus de PA, ajouter un message 'Appyuez sur 't' pour finir le tour'. Sinon on ne sait vraiment pas quoi faire

**Comment by skeggib** [comment]
Tu vois tu sais faire (x

**Comment by armiakrajowa** [comment]
Mais oui j'ai galérer a trouve
Le 2 juin 2015 12:10 AM, "Sebastien Klasa" <notifications@github.com> a
écrit :
