### ISSUE TITLE
Details Equipement

### ISSUE THREAD

**Issue by armiakrajowa** [skeggib/ehptmmmorpgsvr#8]
Ca serait bien aussi de pouvoir consulter les statistiques apporter par un objet, au lieu de devoir l'equiper et ainsi de suite pour voir ce qu'il apporter, si tu vois ce que je veux dire?

**Comment by skeggib** [comment]
Pas de problème.

**Comment by skeggib** [comment]
Je peut afficher les caractéristiques sans problèmes mais j'aimerais aussi afficher les changement de tes stats si tu équipe l'objet, ex :

Epee
Impact : 3 (-1)

Epee a 3 d'impact mais l'arme déjà équipée en a 4 (donc ça va enlever 1).

Pour cela j'ai besoin de méthodes dans Equipement :
- getArme()
- getCasque()
- getPantalon()
- ...

**Comment by armiakrajowa** [comment]
J'y ai pensé mais non.. Si on veut ajouter un objet c'est la merde, ça
implique des instanceof de partout..
Le 2 juin 2015 9:24 AM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Ouais c'est ça le problème, soit tu en fais soit j'en fais. Y a une autre
solution : faire en sorte que l'objet que tu veux équiper remplace celui
qui l'est déjà.

**Comment by armiakrajowa** [comment]
Je vais faire l'autre solution, c'est 10fois plus simple !
Le 2 juin 2015 9:30 AM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Laquelle ?

Le mar. 2 juin 2015 à 09:35, armiakrajowa <notifications@github.com> a
écrit :

**Comment by armiakrajowa** [comment]
Remplacer quand on try d'équiper. C'est deux lignes a changé
Le 2 juin 2015 9:47 AM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
J'ai besoin d'un constructeur par copie pour le joueur.

**Comment by armiakrajowa** [comment]
Dans quel but?
Le 2 juin 2015 8:36 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Pour comparer les stats avec ou sans l'objet que l'on veux équiper :

- Je créé une copie du joueur
- Je créé une copie de l'objet
- J'équipe la copie de l'objet à la copie du joueur
- Je compare les stats du joueur et de sa copie
- J'affiche la différence

**Comment by armiakrajowa** [comment]
Mouais, c'est du bidouillage mais bon xD tu le veux pour quand? Du coup
aussi pour les objets?
Le 2 juin 2015 9:52 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Ouais, bah fait le quand tu peut. De tout manière je pense que toute les classes devraient avoir un constructeur par copie, par principe.

**Comment by armiakrajowa** [comment]
Mouais, mais tu as besoin d'un cet class pour ça non?
Le 2 juin 2015 10:15 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :
