### ISSUE TITLE
Nom du type de l'objet

### ISSUE THREAD

**Issue by skeggib** [skeggib/ehptmmmorpgsvr#9]
Fait une méthode qui renvoi le nom du type de l'objet (String).
On peut généraliser en renvoyant "Vetement" pour tout les vêtement,
"Arme" pour toute les armes et "Potion" pour toute les potions.

Pour cela il suffit que tu fasse un méthode abstraite dans Objet,
puis que tu l'implémente dans Vetement, Arme, et Potion.

**Comment by armiakrajowa** [comment]
Merci, prend moi pour un con :)
Le 2 juin 2015 9:00 AM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
Bah vu que l'on s'est engueulé pour ça je préfère être claire ^^

**Comment by armiakrajowa** [comment]
Non mais c'est a propos de l'explication genre "pense bien a l'héritage
hein"..
Le 2 juin 2015 9:32 AM, "Sebastien Klasa" <notifications@github.com> a
écrit :

**Comment by skeggib** [comment]
C'était juste pour dire qu'il suffit que tu le fasse dans Vetement, Arme, et Potion. Ça sert à rien d'aller plus loin et de la faire dans Pantalon, Gant, etc... Je ne me fou pas de ta gueule je me suis juste mal exprimé.

**Comment by armiakrajowa** [comment]
Rigole hein ^^
Le 2 juin 2015 10:14 PM, "Sebastien Klasa" <notifications@github.com> a
écrit :
